### PR TITLE
[UnusedArgument] Fix false positive when fields accept arguments (#84)

### LINKED ISSUE #84: GraphQL/UnusedArgument should respect arguments tied to a particular field
When arguments added to a field like below:
```
field :my_field, String, null: false do
  argument :my_options, [MyOption]
end

def resolve 
  ::AcceptableData::CreateCommand.call
end
```

rubocop-graphql recognises the `GraphQL/UnusedArgument` offense:

```
Offenses:

app/graphql/mutations/create_my_data.rb:22:5: C: [Correctable] GraphQL/UnusedArgument: Argument my_options: should be listed in the resolve signature.
    def resolve ...
    ^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by Darhazer**
Fixes #84

### CODE REVIEW

File: spec/rubocop/cop/graphql/unused_argument_spec.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ class Input < GraphQL::Schema::InputObject
 
           argument :arg1, String, required: true
           argument :arg2, String, required: false
-          argunent :arg3, Input, required: true
```
Comment (DmitryTsepelev) [inline spec/rubocop/cop/graphql/unused_argument_spec.rb:18]: 😅

**Review by DmitryTsepelev — APPROVED** [review]
LGTM! Thank you!
