### PR TITLE
Fix GraphQL/UnusedArgument cop to respect loads and as keyword

### LINKED ISSUE #64: GraphQL/UnusedArgument false positives for auto-loading arguments
For mutation classes, you can specify `loads:` and `as:` options to its arguments to automatically load an object by its ID, and then alias the argument name sent to the `resolve` method:
https://graphql-ruby.org/mutations/mutation_classes#auto-loading-arguments

Example from the docs:
```
class Mutations::AddStar < Mutations::BaseMutation
  argument :post_id, ID, loads: Types::Post, as: :something

  field :post, Types::Post

  def resolve(something:)
    something.star

    {
      post: something
    }
  end
end
```

Currently this example results in an incorrect `GraphQL/UnusedArgument: Argument post_id: should be listed in the resolve signature` rule violation.

The same error also occurs when `as` is not specified, and the default auto-loaded `post` argument is used.

Example from the docs:
```
class Mutations::AddStar < Mutations::BaseMutation
  argument :post_id, ID, loads: Types::Post

  field :post, Types::Post

  def resolve(post:)
    post.star

    {
      post: post,
    }
  end
end
```

### PR DESCRIPTION
**Pull request by aishek**
Fix [missing](https://github.com/DmitryTsepelev/rubocop-graphql/pull/61#issuecomment-1004033377) `loads` and `as` keywords handle in argument definition.

Fixes #64 

/cc @jgrau

### CODE REVIEW

File: lib/rubocop/cop/graphql/unused_argument.rb [hunk 1]
```diff
@@ -119,6 +128,19 @@ def arg_end(node)
...
+          when /_id$/
+            name_as_string.sub(/_id$/, "").to_sym
+          when /_ids$/
+            name_as_string.sub(/_ids$/, "")
+                          .sub(/([^s])$/, "\\1s")
+                          .to_sym
+          else
+            name
+          end
+        end
```
Comment (aishek) [inline lib/rubocop/cop/graphql/unused_argument.rb:142]: This was copypasted from https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/member/has_arguments.rb#L25-L34. Not sure if some `NOTE: ...` comment required here

**Comment by justisb** [comment]
@aishek the `loads` handling looks great, though could this also handle when an `as` alias is in place?

If useful for testing, both the code blocks from the docs linked in the related issue https://github.com/DmitryTsepelev/rubocop-graphql/issues/64 should pass.

**Comment by aishek** [comment]
> @aishek the `loads` handling looks great, though could this also handle when an `as` alias is in place?

Oh, sorry, I've missed it too.

Fixed.

**Review by DmitryTsepelev — APPROVED** [review]
